version: '3.8'

# Définition des réseaux pour isoler les environnements
networks:
  management_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
  corporate_lan:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
  dmz_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24
  iot_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24

services:
  # === Machine Kali Linux (Machine d'attaque principale) ===
  kali_linux:
    image: kalilinux/kali-rolling:latest
    container_name: kali_linux
    hostname: kali
    # Configuration des ressources pour réduire la consommation
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    volumes:
      - kali_data:/root
      - ./shared_files:/shared
    networks:
      management_network:
        ipv4_address: 10.10.10.10
      corporate_lan:
        ipv4_address: 192.168.1.100
    ports:
      - "2222:22"  # SSH
      - "6080:6080"  # NoVNC
    environment:
      - TZ=Europe/Paris
    command: >
      bash -c "apt update && 
              apt install -y --no-install-recommends 
              openssh-server novnc x11vnc xfce4 firefox-esr 
              nmap metasploit-framework wireshark burpsuite 
              sqlmap dirb && 
              mkdir -p /run/sshd && 
              echo 'root:kali' | chpasswd && 
              sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && 
              service ssh start && 
              x11vnc -create -forever -passwd kali -display :1 & 
              /usr/share/novnc/utils/launch.sh --vnc localhost:5900 --listen 6080 & 
              DISPLAY=:1 startxfce4 & 
              while true; do sleep 3600; done"

  # === Infrastructure réseau ===
  router:
    image: frrouting/frr:latest
    container_name: router
    hostname: router
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    # Configuration des ressources pour réduire la consommation
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    networks:
      corporate_lan:
        ipv4_address: 192.168.1.1
      dmz_network:
        ipv4_address: 172.16.1.1
      iot_network:
        ipv4_address: 192.168.2.1
      management_network:
        ipv4_address: 10.10.10.1
    command: >
      bash -c "sysctl -w net.ipv4.ip_forward=1 && 
              /usr/lib/frr/docker-start"

  # === Workstation Windows simplifiée (Client vulnérable) ===
  windows_client:
    image: alpine:latest  # Version légère avec simulation de Windows
    container_name: windows_client
    hostname: win-client
    # Configuration des ressources pour réduire la consommation
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
    networks:
      corporate_lan:
        ipv4_address: 192.168.1.10
    command: >
      sh -c "apk add --no-cache python3 && 
            python3 -m http.server 80 & 
            while true; do sleep 3600; done"  # Keep container running

volumes:
  kali_data:
