version: '3.8'

networks:
  management_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.99.10.0/24
  corporate_lan:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.99.0/24
  dmz_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.99.0/24
  iot_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.98.0/24

services:
  kali_linux:
    image: kalilinux/kali-rolling:latest
    container_name: kali_linux
    hostname: kali
    ports:
      - "2222:22"
      - "6080:6080"
      - "5901:5901"  # Port VNC direct
    volumes:
      - ./kali_setup.sh:/kali_setup.sh
    command: bash -c "chmod +x /kali_setup.sh && /kali_setup.sh"
    networks:
      management_network:
        ipv4_address: 10.99.10.10
      corporate_lan:
        ipv4_address: 192.168.99.10
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  router:
    image: frrouting/frr:latest
    container_name: router
    hostname: router
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    networks:
      corporate_lan:
        ipv4_address: 192.168.99.1
      dmz_network:
        ipv4_address: 172.16.99.1
      iot_network:
        ipv4_address: 192.168.98.1
      management_network:
        ipv4_address: 10.99.10.1
    command: >
      bash -c "sysctl -w net.ipv4.ip_forward=1 && 
              /usr/lib/frr/docker-start"
    restart: unless-stopped

  windows_client:
    image: alpine:latest
    container_name: windows_client
    hostname: win-client
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
    networks:
      corporate_lan:
        ipv4_address: 192.168.99.20
    command: >
      sh -c "apk add --no-cache python3 && 
            python3 -m http.server 80 & 
            while true; do sleep 3600; done"
    restart: unless-stopped

volumes:
  kali_data:
