version: '3.8'

# Ce fichier dépend du module Core et ajoute les composants de surveillance et détection

networks:
  management_network:
    external: true
  corporate_lan:
    external: true

services:
  # === Système de détection d'intrusion (Snort IDS) ===
  snort:
    image: linton/docker-snort:latest
    container_name: snort
    hostname: snort
    # Configuration des ressources pour réduire la consommation
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    volumes:
      - ./snort/rules:/etc/snort/rules
      - ./snort/log:/var/log/snort
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      management_network:
        ipv4_address: 10.10.10.30
      corporate_lan:
        ipv4_address: 192.168.1.30

  # === Elasticsearch (version légère) ===
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    hostname: elasticsearch
    # Configuration des ressources pour réduire la consommation
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 1G
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      management_network:
        ipv4_address: 10.10.10.31
    ports:
      - "9200:9200"

  # === Kibana (optionnel, peut être désactivé pour économiser des ressources) ===
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    container_name: kibana
    hostname: kibana
    # Configuration des ressources pour réduire la consommation
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      management_network:
        ipv4_address: 10.10.10.32
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  # === Filebeat pour la collecte de logs (version légère) ===
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.0
    container_name: filebeat
    hostname: filebeat
    # Configuration des ressources pour réduire la consommation
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./snort/log:/var/log/snort:ro
    networks:
      management_network:
        ipv4_address: 10.10.10.33
    command: filebeat -e -strict.perms=false
    depends_on:
      - elasticsearch

volumes:
  esdata:
